<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ComposerAutoloaderInitb85db472c157123affdf8206a8e93869' => $vendorDir . '/composer/autoload_real.php',
    'Composer\\Autoload\\ClassLoader' => $vendorDir . '/composer/ClassLoader.php',
    'Composer\\Autoload\\ComposerStaticInitb85db472c157123affdf8206a8e93869' => $vendorDir . '/composer/autoload_static.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'connection' => $baseDir . '/core/database/connection.php',
    'pagescontroller' => $baseDir . '/controllers/pagescontroller.php',
    'querybuilder' => $baseDir . '/core/database/querybuilder.php',
    'request' => $baseDir . '/core/database/request.php',
    'router' => $baseDir . '/core/router.php',
);
